// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Cypress = require("@nobleai/rescript-cypress/src/cypress.bs.js");

var cy = window.cy;

function c(param, param$1) {
  return Cypress.visit(cy, "https://www.881903.com/live/903", param, param$1);
}

exports.cy = cy;
exports.c = c;
/* cy Not a pure module */
